# Generated by Django 5.2.17 on 2026-09-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.CharField(max_length=50, unique=True)),
                ('fund_name', models.CharField(max_length=200)),
                ('fund_type', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
