# Generated by Django 5.2.17 on 2026-10-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_fundhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='country',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fund',
            name='currency',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='fund',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=50),
        ),
    ]
